INSERT INTO department (name)
VALUES  ('Engineering'),
        ('Sales'), 
        ('Marketing'),
        ('Finance'),
        ('Operations'),
        ('Legal'),
        ('Human Resources'),
        ('Customer Support'),  
        ('Research'),
        ('Executive');

INSERT INTO role (title, salary, department_id)
VALUES  ('Lead Engineer', 150000, 1),
        ('Software Engineer', 120000, 1),
        ('Sales Lead', 100000, 2),
        ('Salesperson', 80000, 2),
        ('Lead Marketer', 150000, 3),
        ('Marketer', 100000, 3),
        ('Accountant', 125000, 4),
        ('Legal Team Lead', 250000, 6),
        ('Lawyer', 190000, 6),
        ('HR Manager', 160000, 7),
        ('HR Assistant', 80000, 7),
        ('Customer Support', 70000, 8),
        ('Research Team Lead', 250000, 9),
        ('Researcher', 150000, 9),
        ('Executive Assistant', 100000, 10);

INSERT INTO employee (first_name, last_name, role_id, manager_id)
VALUES  ('John', 'Doe', 1, null),
        ('Mike', 'Chan', 2, 1),
        ('Ashley', 'Rodriguez', 3, null),
        ('Kevin', 'Tupik', 4, 3),
        ('Kunal', 'Singh', 5, null),
        ('Malia', 'Brown', 6, 5),
        ('Sarah', 'Lourd', 7, 15),
        ('Tom', 'Allen', 8, null),
        ('Christian', 'Eckenrode', 9, 8),
        ('Jennifer', 'Aniston', 10, null),
        ('John', 'Doe', 11, 10),
        ('Mike', 'Chan', 12, 15),
        ('Ashley', 'Rodriguez', 13, null),
        ('Kevin', 'Tupik', 14, 13),
        ('Kunal', 'Singh', 15, null),
        ('Malia', 'Brown', 2, 1),
        ('Sarah', 'Lourd', 9, 8),
        ('Tom', 'Allen', 14, 13),
        ('Christian', 'Eckenrode', 2, 1),
        ('Jennifer', 'Aniston', 12, 15);